name: todo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  toggle_switch: ^2.3.0
  introduction_screen: ^3.1.14
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.8.0
  easy_localization: ^3.0.7
  provider: ^6.1.2
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.4
  google_sign_in: ^6.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

